server:
  port: 8082

kafka:
  topic:
    user-notifications: user.notifications

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

notification:
  mail:
    from: example@male.com

logging:
  level:
    org.notification: INFO