server:
  port: 8082

kafka:
  topic:
    user-notifications: user.notifications

spring:
  mail:
    host: localhost
    port: 3025
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

notification:
  mail:
    from: example@mail.com

logging:
  level:
    org.notification: INFO